### ISSUE TITLE
make runtest fails

### ISSUE THREAD

**Issue by aravindhm** [tinghuiz/appearance-flow#2]
Test routines after caffe installation report the following failures

[  FAILED  ] 7 tests, listed below:
[  FAILED  ] ResizeLayerTest/2.TestGradient, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] ResizeLayerTest/3.TestGradient, where TypeParam = caffe::GPUDevice<double>
[  FAILED  ] RemapLayerTest/2.TestRemapGradient, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] LayerFactoryTest/0.TestCreateLayer, where TypeParam = caffe::CPUDevice<float>
[  FAILED  ] LayerFactoryTest/1.TestCreateLayer, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] LayerFactoryTest/2.TestCreateLayer, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] LayerFactoryTest/3.TestCreateLayer, where TypeParam = caffe::GPUDevice<double>

Platform details:
Cuda-8.0 with cudnn v5. GPU device is a Titan Z.

Commands used:
make all -j8
make test // This results in compilation errors which are fixed by changing some header files.
make runtest

**Comment by tinghuiz** [comment]
Hi, could you provide more details on how you fixed the errors?

**Comment by aravindhm** [comment]
I changed the header files in caffe/src/caffe/test/ to fix missing ones.

The output of `git diff caffe/src/caffe/test > patch` is attached below:

[patch.txt](https://github.com/tinghuiz/appearance-flow/files/716403/patch.txt)

**Comment by peri044** [comment]
Hi, I'm facing the similar issue. 

`src/caffe/test/test_layer_factory.cpp:47: Failure
Value of: layer->type()
Actual: ""
Expected: iter->first
Which is: "DataAugmentation"
[ FAILED ] LayerFactoryTest/3.TestCreateLayer, where TypeParam = caffe::GPUDevice<double> (11 ms)

......

[----------] Global test environment tear-down
[==========] 1935 tests from 263 test cases ran. (319275 ms total)
[ PASSED ] 1931 tests.
[ FAILED ] 4 tests, listed below:
[ FAILED ] LayerFactoryTest/0.TestCreateLayer, where TypeParam = caffe::CPUDevice<float>
[ FAILED ] LayerFactoryTest/1.TestCreateLayer, where TypeParam = caffe::CPUDevice<double>
[ FAILED ] LayerFactoryTest/2.TestCreateLayer, where TypeParam = caffe::GPUDevice<float>
[ FAILED ] LayerFactoryTest/3.TestCreateLayer, where TypeParam = caffe::GPUDevice<double>
4 FAILED TESTS
make: *** [runtest] Error 1`

Could you please elaborate which header files are you referring to? 
In the caffe/src/caffe/test folder I can't find the test_array.cpp, test_remap_layer.cpp, test_resize_layer.cpp files mentioned in the patch.txt for which the headers have to be changed.

Thanks,

**Comment by citlag** [comment]
I have same issue as you @Peri044 HELP!

**Comment by gonzalegit** [comment]
I do had the same issue as you @Peri044 and @citlag , Please HELP!!

**Comment by QueenJuliaZxx** [comment]
Have anybpdy solved it？

**Comment by polo5** [comment]
+1
